<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TypingTextSeeder extends Seeder
{
    public function run(): void
    {
        // dzēšam iepriekšējos ierakstus
        DB::table('typing_texts')->truncate();

        $texts = [
            // 🟢 EASY (≈50 words)
            ['mode' => 'easy', 'text' => "the cat runs fast it jumps over the small dog they play in the garden all day long the sun is warm and bright we have fun and learn new words every time"],
            ['mode' => 'easy', 'text' => "i like to read books and write short stories the birds sing in the morning the children laugh and run around the park it is a happy day"],
            ['mode' => 'easy', 'text' => "she walks to school with her friends they carry their bags and talk about games and songs they enjoy the fresh air and the sunny sky"],

            // 🟡 MEDIUM (≈100 words)
            ['mode' => 'medium', 'text' => "every morning i wake up and drink water i brush my teeth and eat breakfast then i walk to the bus stop i listen to music while waiting i watch people and notice the trees and flowers the city is alive and full of sounds i try to remember all the small details on my way to school it helps me practice focus and patience i like to observe the world and write small notes about everything i see later i read books and do exercises it is important to practice every day to get better"],
            ['mode' => 'medium', 'text' => "my friends and i like to play games in the afternoon we run and jump we laugh and talk about our plans we share our snacks and enjoy the sun the park is quiet and calm we sometimes read stories or draw pictures we help each other and learn new skills together it is a good way to spend time outside and have fun while practicing our concentration and memory we try to play fair and follow the rules of every game we like to explore new ideas and solve simple problems every day we learn something new"],
            ['mode' => 'medium', 'text' => "i enjoy typing simple sentences on the keyboard it helps me move my fingers faster i pay attention to each letter and word i make small mistakes and correct them it is a good exercise for my brain i read and write every day and try to improve my skills i set small goals and practice regularly i focus on accuracy and then i try to increase speed i feel satisfied when i finish a text without errors i like to challenge myself with longer paragraphs i enjoy learning new words and forming sentences it is a calm and useful activity"],

            // 🔴 HARD (≈150 words)
            ['mode' => 'hard', 'text' => "typing is an important skill for every student and worker it allows us to write ideas quickly and communicate with others we practice daily to improve speed and accuracy long texts are helpful because they teach patience and focus we start slowly and increase speed over time it is good to notice mistakes and learn from them every day we type letters words and sentences we try to use new words and create meaningful texts it is important to stay calm and keep concentration distractions make us slow down we take short breaks and stretch our hands it is useful to keep a notebook and write small notes we review our texts and correct errors learning to type properly takes time and dedication we repeat exercises and enjoy seeing progress in our writing and thinking abilities"],
            ['mode' => 'hard', 'text' => "practicing typing helps our brain and hands work together we start with simple exercises and move to longer passages we pay attention to each key and try not to look at the keyboard repetition makes us better we learn common words and patterns we try to stay relaxed and avoid tension it is important to have comfortable posture and good lighting we can listen to calm music to focus we time ourselves and record results we challenge ourselves to type faster without mistakes we read texts and rewrite them we explore new topics and write sentences with different structures it is a useful habit to keep and improve every week we notice that speed and accuracy increase gradually it is rewarding to see improvements"],
            ['mode' => 'hard', 'text' => "learning to type efficiently requires focus and regular practice we write paragraphs that include common words numbers and simple sentences we avoid looking at the keyboard and trust our memory we correct mistakes immediately and try again we notice our rhythm and try to keep it steady we record our time and errors we compete with ourselves to improve we practice different texts and topics it is important to take breaks and rest our hands we stretch fingers wrists and shoulders we try to keep calm even if we make mistakes consistency and patience are key qualities we keep track of progress and feel proud of achievements we type every day and see results over time it is a skill that helps in school work and personal projects"],

            // ⚫ HARDCORE (≈300 words)
            ['mode' => 'hardcore', 'text' => "advanced typing practice is very useful for anyone who wants to type fast and without mistakes we start with long passages and try to stay focused we write texts about different subjects we notice the position of our fingers and move them efficiently we try to keep a steady rhythm and breathe calmly distractions are ignored we pay attention to every word and letter we correct errors quickly and continue we record our time and compare results from previous sessions we challenge ourselves with more difficult texts we observe improvement in speed and accuracy over weeks we keep practicing daily and develop discipline this exercise helps memory concentration and patience we use all our fingers and coordinate eyes hands and mind we feel satisfaction when we complete a long text without mistakes we can type messages letters stories or reports quickly and correctly we notice how typing becomes easier and more natural we stay calm and enjoy the process we feel confident and skilled we continue to practice and refine our abilities each day we develop endurance focus and precision this skill is valuable for work school and personal projects it gives us control over written communication and makes writing faster easier and enjoyable"],
            ['mode' => 'hardcore', 'text' => "professional typists practice every day to maintain high speed and accuracy they write texts about many topics they pay attention to rhythm and finger movements they take short breaks to avoid fatigue they stretch hands and wrists and adjust posture distractions are ignored they focus on every letter and word they measure their time and record errors they challenge themselves with harder passages they observe progress over weeks they improve coordination concentration and memory they learn new words and typing patterns daily they feel satisfaction when typing long texts without mistakes they can write code letters reports stories or messages quickly they continue to train and develop endurance they stay calm and disciplined typing becomes automatic and efficient they feel confident and capable of handling any writing task they keep practicing to maintain and improve skills over time"],
            ['mode' => 'hardcore', 'text' => "typing at the highest level requires daily practice patience and focus we write long passages with different words and structures we pay attention to accuracy and speed we correct mistakes immediately and continue typing we keep hands relaxed and maintain good posture we coordinate eyes hands and mind we record our results and try to improve each session we challenge ourselves with longer and more difficult texts we develop discipline concentration and memory we practice regularly and observe gradual improvement we feel confident when typing without errors we can write texts letters reports stories and messages efficiently we continue practicing every day we enjoy the process and feel satisfaction we become skilled and capable our typing becomes automatic fast and accurate we maintain focus and rhythm we refine techniques and develop endurance we feel proud of our achievements and continue to grow our abilities in writing and communication"],
        ];

        DB::table('typing_texts')->insert($texts);
    }
}
